# Site settings
title: New South Wales wine regions
client:
  name: Destination New South Wales
  link: https://www.visitnsw.com/?utm_source=partnerlandingpage&utm_medium=website&utm_campaign=SecretEscapesUK
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Discover a place of rolling vineyards and cellar door tastings, gorgeous countryside and delicious foodie experiences in New South Wales. A vibrant collection of regions produce some of Australia’s finest wines, all a short hop from the state’s buzzing gateway, Sydney. Although we can’t travel to New South Wales right now, it’s still a great time to plan an adventure that takes in the best of the state, matching a city escape with unforgettable excursions into the heart of wine country. Our favourite vintners can’t wait to welcome you back to New South Wales, so read on as they share their top tips for each area.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/new-south-wales-wine" # the subpath of the site, including territory and year
img:     "/uk/2020/new-south-wales-wine/_assets/img"
css:     "/uk/2020/new-south-wales-wine/_assets/css"
js:      "/uk/2020/new-south-wales-wine/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed